### ISSUE TITLE
deepmerge of options makes it impossible to overwrite

### ISSUE THREAD

**Issue by timkelty** [barraponto/neutrino-preset-stylelint#1]
Didn't want to lint my output, just my source.

```
  neutrino.use(stylelint, {
    files: [path.join(neutrino.options.source +  '**/*.+css')],
  });
```

Doesn't work though, because of the use of `deepmerge`, which by default also merges arrays :(

**Comment by barraponto** [comment]
@constgen provided a solution here https://github.com/barraponto/neutrino-preset-stylelint-standard/pull/1 see if that works for you (i'll fix it if it does)

**Comment by timkelty** [comment]
Finally got around to testing - this works for me 👍 

Worth noting - it solves my use-case, but doesn't necessarily address the core issue. That is, if someone wanted to overwrite your `files` setting, they would be unable, because `deepmerge` is going to merge arrays together by default.

**Comment by barraponto** [comment]
I see. It's an easy fix though :)
